"""empty message.

Revision ID: bc06f4ddafef
Revises: f8d4e44e10c2
Create Date: 2025-11-30 21:40:15.397214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc06f4ddafef'
down_revision = 'f8d4e44e10c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammonia_ppm', sa.Float(), nullable=False, comment='Ammonia level in ppm'),
    sa.Column('h2s_ppm', sa.Float(), nullable=False, comment='H2S level in ppm'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='Temperature in Celsius'),
    sa.Column('humidity', sa.Float(), nullable=False, comment='Relative humidity percentage'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of reading'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_created_at'), 'sensor_readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_created_at'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
